# Generated by Django 5.2.8 on 2026-04-03 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offline_monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('ended', 'Ended')], default='running', max_length=20)),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_session', to='offline_monitoring.offlineexam')),
            ],
            options={
                'db_table': 'monitoring_sessions',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('mobile_phone', 'Mobile Phone Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('looking_away', 'Looking Away'), ('external_paper', 'External Paper Detected'), ('voice_detected', 'Voice Detected'), ('head_movement', 'Excessive Head Movement')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='alerts/snapshots/')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='offline_monitoring.studentzone')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ai_detection.monitoringsession')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_alerts', models.PositiveIntegerField(default=0)),
                ('high_severity', models.PositiveIntegerField(default=0)),
                ('medium_severity', models.PositiveIntegerField(default=0)),
                ('low_severity', models.PositiveIntegerField(default=0)),
                ('violation_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='ai_detection.monitoringsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'violation_logs',
                'unique_together': {('student', 'session')},
            },
        ),
    ]
