# Generated by Django 5.2.8 on 2026-04-07 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offline_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='camera',
            table='H_cameras',
        ),
        migrations.AlterModelTable(
            name='examhall',
            table='H_exam_halls',
        ),
        migrations.AlterModelTable(
            name='offlineexam',
            table='H_offline_exams',
        ),
        migrations.AlterModelTable(
            name='studentzone',
            table='H_student_zones',
        ),
    ]
