# Generated by Django 5.2.8 on 2026-04-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_monitoring', '0004_alter_hallenrollment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallenrollment',
            name='seat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
