# Generated by Django 5.2.8 on 2026-04-16 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_monitoring', '0008_alter_hallenrollment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentzone',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentzone',
            name='student',
        ),
        migrations.AddField(
            model_name='studentzone',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='offline_monitoring.examhall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentzone',
            name='student_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentzone',
            name='student_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentzone',
            name='seat_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
