# Generated by Django 5.2.8 on 2026-04-22 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_monitoring', '0010_studentzone_camera_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examhall',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_halls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentzone',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='offline_monitoring.camera'),
        ),
    ]
