# Generated by Django 5.2.8 on 2026-06-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('mobile_phone', 'Mobile Phone Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('no_face', 'No Face Detected'), ('looking_away', 'Looking Away'), ('external_paper', 'External Paper Detected'), ('voice_detected', 'Voice Detected'), ('head_movement', 'Excessive Head Movement'), ('manual_flag', 'Manual Proctor Flag')], max_length=50),
        ),
    ]
