# Generated by Django 5.2.8 on 2026-04-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentFaceEmbedding',
        ),
    ]
