# Generated by Django 5.2.8 on 2026-05-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_add_risk_score_to_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='security_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Per-exam proctoring module settings (behavior_detection, audio_detection, etc.)'),
        ),
    ]
