# Generated by Django 5.2.8 on 2026-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_add_grading_status_to_examresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='termination_reason',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
