# Generated by Django 5.2.8 on 2026-04-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='face_embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
