# Generated by Django 5.2.8 on 2026-02-21 23:50

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.professor_upload_path),
        ),
        migrations.AlterField(
            model_name='professor',
            name='identity_card',
            field=models.ImageField(upload_to=authentication.models.professor_upload_path),
        ),
    ]
