# Generated by Django 5.2.8 on 2026-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_professor_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='real_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
