# Generated by Django 5.2.8 on 2026-03-12 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_baseuser_real_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='custom_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'professor'}, on_delete=django.db.models.deletion.CASCADE, related_name='professor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
