# Generated by Django 5.2.8 on 2026-05-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violation_Exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='violationbehavior',
            name='snapshot',
            field=models.TextField(blank=True, help_text='Base64 JPEG of the camera frame at the time of violation', null=True),
        ),
        migrations.AlterField(
            model_name='violationbehavior',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy_paste', 'Copy / Paste Attempt'), ('devtools', 'Developer Tools Opened'), ('fullscreen_exit', 'Exited Fullscreen'), ('keyboard_shortcut', 'Blocked Keyboard Shortcut'), ('right_click', 'Right Click Attempt'), ('drag_select', 'Drag / Select Attempt'), ('ai_head_pose', 'AI: Suspicious Head Movement'), ('ai_multiple_faces', 'AI: Multiple Faces Detected'), ('ai_object_detected', 'AI: Unauthorized Object Detected'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
