# Generated by Django 6.0.2 on 2026-03-07 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_alter_class_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject',
        ),
    ]
