# Generated by Django 5.2.8 on 2026-04-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offline_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connecting', 'Connecting'), ('live', 'Live'), ('stopped', 'Stopped'), ('error', 'Error')], default='connecting', max_length=20)),
                ('fps', models.FloatField(default=0)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_sessions', to='offline_monitoring.camera')),
            ],
            options={
                'db_table': 'stream_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
