# Generated by Django 5.2.8 on 2026-04-26 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0005_alter_exam_professor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEventViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheating_detected', models.BooleanField(default=True)),
                ('cheating_reason', models.CharField(blank=True, help_text='Human-readable AI verdict, e.g. "LOOKING LEFT | OBJECT: phone"', max_length=255, null=True)),
                ('head_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('head_suspicious', models.BooleanField(default=False)),
                ('yolo_suspicious', models.BooleanField(default=False)),
                ('yolo_labels', models.JSONField(blank=True, default=list, help_text='List of YOLO detection labels, e.g. ["phone", "book"]')),
                ('h_ratio', models.FloatField(default=0.0)),
                ('v_ratio', models.FloatField(default=0.0)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_violations', to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_event_violation',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ViolationBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy_paste', 'Copy / Paste Attempt'), ('devtools', 'Developer Tools Opened'), ('fullscreen_exit', 'Exited Fullscreen'), ('keyboard_shortcut', 'Blocked Keyboard Shortcut'), ('right_click', 'Right Click Attempt'), ('drag_select', 'Drag / Select Attempt'), ('other', 'Other')], default='other', max_length=30)),
                ('score_points', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('details', models.CharField(blank=True, help_text='Human-readable reason, e.g. reason string from frontend', max_length=255, null=True)),
                ('cumulative_score', models.DecimalField(decimal_places=1, default=0, help_text='Total violation score at the time of this event', max_digits=5)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_behaviors', to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violation_behaviors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'violation_behavior',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
