# Generated by Django 5.2.8 on 2026-05-04 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_add_risk_score_to_examresult'),
        ('violation_Exam', '0002_violationbehavior_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationbehavior',
            name='event_type',
            field=models.CharField(choices=[('tab_switch', 'Tab Switch'), ('copy_paste', 'Copy / Paste Attempt'), ('devtools', 'Developer Tools Opened'), ('fullscreen_exit', 'Exited Fullscreen'), ('keyboard_shortcut', 'Blocked Keyboard Shortcut'), ('right_click', 'Right Click Attempt'), ('drag_select', 'Drag / Select Attempt'), ('ai_head_pose', 'AI: Suspicious Head Movement'), ('ai_multiple_faces', 'AI: Multiple Faces Detected'), ('ai_object_detected', 'AI: Unauthorized Object Detected'), ('ai_audio_violation', 'AI: Abnormal Sound Detected'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.CreateModel(
            name='AudioViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('loud_noise', 'Loud Noise Detected'), ('speech_detected', 'Speech / Talking Detected'), ('multiple_speakers', 'Multiple Speakers Detected')], default='loud_noise', max_length=30)),
                ('db_level', models.FloatField(default=0.0, help_text='Sound level in dBFS at the time of the event')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_violations', to='exam.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_violations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audio_violation',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
