# Generated by Django 5.2.8 on 2026-05-04 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_add_risk_score_to_examresult'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('1day', '1 Day Before'), ('1hour', '1 Hour Before'), ('10min', '10 Minutes Before')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='exam.exam')),
            ],
            options={
                'db_table': 'exam_reminder_logs',
                'unique_together': {('exam', 'reminder_type')},
            },
        ),
    ]
