# Generated by Django 5.2.8 on 2026-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_examreminderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreminderlog',
            name='reminder_type',
            field=models.CharField(choices=[('1day', '1 Day Before (in-app)'), ('1day_email', '1 Day Before (email)'), ('1hour', '1 Hour Before'), ('10min', '10 Minutes Before')], max_length=20),
        ),
    ]
