# Generated by Django 5.2.8 on 2026-04-17 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_monitoring', '0009_remove_studentzone_exam_remove_studentzone_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentzone',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='offline_monitoring.camera'),
        ),
    ]
