# Generated by Django 5.2.8 on 2026-06-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offline_monitoring', '0011_examhall_professor_alter_studentzone_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineexam',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('missed', 'Missed')], default='upcoming', max_length=20),
        ),
    ]
