# Generated by Django 5.2.8 on 2026-03-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('instructors', '0004_classenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='instructors.class'),
        ),
    ]
