# Generated by Django 5.2.8 on 2026-03-19 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_examresult_studentanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
