# Generated by Django 5.2.8 on 2026-04-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_alter_exam_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='risk_score',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Normalised risk score 0-100 computed by RiskEngine at submit time', max_digits=5),
        ),
    ]
