# Generated by Django 5.2.8 on 2026-05-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_add_security_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='grading_status',
            field=models.CharField(choices=[('auto', 'Auto Graded'), ('pending', 'Pending'), ('graded', 'Graded')], default='auto', help_text='auto = fully auto-graded; pending = has ungraded essays; graded = instructor finished', max_length=10),
        ),
    ]
